export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGGING_IN_USER = 'LOGGING_IN_USER';

export const ADD_FAVORITE_TEAM = 'ADD_FAVORITE_TEAM';
export const REMOVE_FAVORITE_TEAM = 'REMOVE_FAVORITE_TEAM';
